In [1]:
import numpy as np
import time
n = 100
m = 100
q = 100
ran_max = 10
X = np.random.randint(ran_max, size=(n, m))
Y = np.random.randint(ran_max, size=(m, q))
s = (m, q)
result1 = np.zeros(s)
start_time1 = time.time()

# the most standart algorithm of matrix multiplication 

for i in range(len(X)):
   for j in range(len(Y[0])):
       for k in range(len(Y)):
           result1[i][j] += X[i][k] * Y[k][j]
finish_time1 = time.time()
print(result1)
print("Seconds by standart algorithm =", finish_time1 - start_time1)

[[2330. 2081. 2011. ... 1952. 2041. 2015.]
 [2233. 2207. 2108. ... 2060. 1954. 2084.]
 [1993. 1854. 2008. ... 1637. 1774. 1933.]
 ...
 [1757. 1816. 1711. ... 1544. 1585. 1870.]
 [2200. 2083. 2084. ... 2117. 2014. 1982.]
 [2069. 1804. 1782. ... 1786. 1784. 1954.]]
Seconds by standart algorithm = 1.007336139678955


In [2]:
#If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred
result1 = np.zeros(s)
start_time2 = time.time()
result2 = np.matmul(X,Y)
finish_time2 = time.time()
print("Seconds matmul =", finish_time2 - start_time2)



Seconds matmul = 0.0029647350311279297


In [3]:
#Try numpy.dot
start_time3 = time.time()
result1 = np.dot(X,Y)
finish_time3 = time.time()
print("Seconds dot =", finish_time3 - start_time3)

Seconds dot = 0.0010170936584472656


In [4]:

result1 = np.zeros(s)
#the idea of the method is to transpose the matrix
# as we see it works quicker
start_time2 = time.time()
Y = np.transpose(Y)
for i in range(n):
    for j in range(q):
        result1[i][j] = np.sum([a*b for a,b in zip(X[i],Y[j])])
finish_time2 = time.time()
print(result1)
print("Seconds by this algorithm =", finish_time2 - start_time2)

[[2330. 2081. 2011. ... 1952. 2041. 2015.]
 [2233. 2207. 2108. ... 2060. 1954. 2084.]
 [1993. 1854. 2008. ... 1637. 1774. 1933.]
 ...
 [1757. 1816. 1711. ... 1544. 1585. 1870.]
 [2200. 2083. 2084. ... 2117. 2014. 1982.]
 [2069. 1804. 1782. ... 1786. 1784. 1954.]]
Seconds by this algorithm = 0.30015110969543457
